import { NextRequest } from "next/server";
import { z } from "zod";
import { db } from "@/lib/db";
import { apiError, apiSuccess } from "@/lib/api";
import { getGuestSession, getOrCreateCart, recordAnalytics } from "@/lib/storefront";

export const runtime = "nodejs";
const schema = z.object({ productId: z.string().cuid(), variantId: z.string().cuid().nullable().optional(), quantity: z.number().int().min(1).max(99) });

export async function GET() { try { const session = await getGuestSession(); const cart = await getOrCreateCart(session); return apiSuccess(cart); } catch (e) { return apiError(e); } }
export async function POST(request: NextRequest) { try { const session = await getGuestSession(); const body = schema.parse(await request.json()); const product = await db.product.findUnique({ where: { id: body.productId }, include: { variants: true } }); if (!product || !product.published || product.status !== "PUBLISHED") return apiError(new Error("Product unavailable")); const variant = body.variantId ? product.variants.find(v => v.id === body.variantId && v.active) : null; const stock = variant?.stock ?? product.stock; if (stock < body.quantity) return apiError(new Error("Insufficient stock")); const cart = await getOrCreateCart(session); const existing = cart.items.find(i => i.productId === body.productId && i.variantId === (body.variantId ?? null)); const quantity = Math.min(stock, (existing?.quantity ?? 0) + body.quantity); if (existing) await db.cartItem.update({ where: { id: existing.id }, data: { quantity } }); else await db.cartItem.create({ data: { cartId: cart.id, productId: body.productId, variantId: body.variantId ?? null, quantity } }); await recordAnalytics("ADD_TO_CART", { productId: body.productId, sessionId: session, metadata: { quantity: body.quantity } }); return apiSuccess(await getOrCreateCart(session)); } catch (e) { return apiError(e); } }
export async function PATCH(request: NextRequest) { try { const body = z.object({ itemId: z.string().cuid(), quantity: z.number().int().min(0).max(99) }).parse(await request.json()); const session = await getGuestSession(); const cart = await getOrCreateCart(session); const item = cart.items.find(i => i.id === body.itemId); if (!item) return apiError(new Error("Cart item not found")); if (body.quantity === 0) await db.cartItem.delete({ where: { id: item.id } }); else await db.cartItem.update({ where: { id: item.id }, data: { quantity: body.quantity } }); return apiSuccess(await getOrCreateCart(session)); } catch (e) { return apiError(e); } }
export async function DELETE(request: NextRequest) { try { const id = z.string().cuid().parse(new URL(request.url).searchParams.get("itemId")); const session = await getGuestSession(); const cart = await getOrCreateCart(session); if (!cart.items.some(i => i.id === id)) return apiError(new Error("Cart item not found")); await db.cartItem.delete({ where: { id } }); await recordAnalytics("REMOVE_FROM_CART", { sessionId: session }); return apiSuccess(await getOrCreateCart(session)); } catch (e) { return apiError(e); } }
