import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { db } from "@/lib/db";
import { ApiError, apiError, apiSuccess } from "@/lib/api";
import { getGuestSession, getOrCreateCart, recordAnalytics, GUEST_COOKIE, sessionCookieOptions } from "@/lib/storefront";

export const runtime = "nodejs";
const itemSchema = z.object({ productId: z.string().cuid(), variantId: z.string().cuid().nullable().optional(), quantity: z.number().int().min(1).max(99) });

export async function GET() { try { const session = await getGuestSession(); const cart = await getOrCreateCart(session); const response = NextResponse.json({ data: cart }); if (!requestHasCookie(session)) response.cookies.set(GUEST_COOKIE, session, sessionCookieOptions()); return response; } catch (e) { return apiError(e); } }
function requestHasCookie(_session: string) { return false; }

export async function POST(request: NextRequest) { try { const body = itemSchema.parse(await request.json()); const session = await getGuestSession(); const cart = await getOrCreateCart(session); const product = await db.product.findFirst({ where: { id: body.productId, published: true, status: "PUBLISHED" }, include: { variants: true } }); if (!product) throw new ApiError("PRODUCT_UNAVAILABLE", "Product is unavailable", 409); const variant = body.variantId ? product.variants.find(v => v.id === body.variantId && v.active) : null; if (body.variantId && !variant) throw new ApiError("VARIANT_UNAVAILABLE", "Selected variant is unavailable", 409); const stock = variant?.stock ?? product.stock; if (stock < body.quantity) throw new ApiError("OUT_OF_STOCK", "Not enough stock", 409); const item = await db.cartItem.upsert({ where: { cartId_productId_variantId: { cartId: cart.id, productId: product.id, variantId: body.variantId ?? null } }, update: { quantity: { increment: body.quantity } }, create: { cartId: cart.id, productId: product.id, variantId: body.variantId ?? null, quantity: body.quantity } }); await recordAnalytics("ADD_TO_CART", { productId: product.id, sessionId: session }); const response = NextResponse.json({ data: item }, { status: 201 }); response.cookies.set(GUEST_COOKIE, session, sessionCookieOptions()); return response; } catch (e) { return apiError(e); } }

export async function PATCH(request: NextRequest) { try { const body = itemSchema.extend({ itemId: z.string().cuid() }).omit({ productId: true, variantId: true }).parse(await request.json()); const session = await getGuestSession(); const cart = await getOrCreateCart(session); const item = await db.cartItem.findFirst({ where: { id: body.itemId, cartId: cart.id } }); if (!item) throw new ApiError("NOT_FOUND", "Cart item not found", 404); if (body.quantity === 0) await db.cartItem.delete({ where: { id: item.id } }); else await db.cartItem.update({ where: { id: item.id }, data: { quantity: body.quantity } }); const response = NextResponse.json({ data: await getOrCreateCart(session) }); response.cookies.set(GUEST_COOKIE, session, sessionCookieOptions()); return response; } catch (e) { return apiError(e); } }

export async function DELETE(request: NextRequest) { try { const itemId = z.string().cuid().parse(new URL(request.url).searchParams.get("itemId")); const session = await getGuestSession(); const cart = await getOrCreateCart(session); const item = await db.cartItem.findFirst({ where: { id: itemId, cartId: cart.id } }); if (!item) throw new ApiError("NOT_FOUND", "Cart item not found", 404); await db.cartItem.delete({ where: { id: item.id } }); await recordAnalytics("REMOVE_FROM_CART", { productId: item.productId, sessionId: session }); const response = NextResponse.json({ data: await getOrCreateCart(session) }); response.cookies.set(GUEST_COOKIE, session, sessionCookieOptions()); return response; } catch (e) { return apiError(e); } }
