import Link from "next/link";
import { db } from "@/lib/db";
import { requireRole } from "@/lib/permissions";

function money(value: number) { return new Intl.NumberFormat("en-NG", { style: "currency", currency: "NGN", maximumFractionDigits: 0 }).format(value / 100); }

export default async function AdminProductsPage() {
  await requireRole("EDITOR");
  const products = await db.product.findMany({ where: { status: { not: "ARCHIVED" } }, include: { images: { orderBy: { position: "asc" }, take: 1 }, category: { select: { name: true } }, brand: { select: { name: true } } }, orderBy: { updatedAt: "desc" } });
  return <main className="mx-auto max-w-7xl space-y-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold uppercase tracking-widest text-enkays-700">Catalog</p><h1 className="mt-1 text-3xl font-bold text-ink-900">Products</h1><p className="mt-2 text-sm text-ink-500">Create, edit, publish and manage your catalog.</p></div><Link href="/admin/products/new" className="rounded-xl bg-enkays-700 px-4 py-2.5 text-center text-sm font-semibold text-white">Add product</Link></div>
    <div className="overflow-hidden rounded-2xl border border-ink-100 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="border-b border-ink-100 bg-ink-50"><tr><th className="px-5 py-3 text-left">Product</th><th className="px-5 py-3 text-left">SKU</th><th className="px-5 py-3 text-left">Price</th><th className="px-5 py-3 text-left">Stock</th><th className="px-5 py-3 text-left">Status</th><th className="px-5 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-ink-100">{products.map((product) => <tr key={product.id} className="hover:bg-ink-50"><td className="px-5 py-4"><div className="flex items-center gap-3">{product.images[0] ? <img src={product.images[0].secureUrl} alt="" className="h-12 w-12 rounded-lg object-cover" /> : <div className="h-12 w-12 rounded-lg bg-ink-100" />}<div><p className="font-semibold text-ink-900">{product.name}</p><p className="text-xs text-ink-500">{product.brand?.name ?? "No brand"} · {product.category?.name ?? "No category"}</p></div></div></td><td className="px-5 py-4 text-ink-600">{product.sku}</td><td className="px-5 py-4 font-medium">{money(product.price)}</td><td className="px-5 py-4">{product.stock}</td><td className="px-5 py-4"><span className="rounded-full bg-ink-100 px-2.5 py-1 text-xs font-medium">{product.status}</span></td><td className="px-5 py-4 text-right"><Link href={`/admin/products/${product.id}`} className="font-semibold text-enkays-700 hover:underline">Edit</Link></td></tr>)}</tbody></table></div>{products.length === 0 && <div className="p-10 text-center text-sm text-ink-500">No products yet.</div>}</div></main>;
}
